### ISSUE TITLE
Save attachment ID for upload fields

### ISSUE THREAD

**Issue by helgatheviking** [devinsays/options-framework-plugin#138]
Putting this here as a reminder to myself to take a look at it.  Ideally I'd like to see the upload fields also save the attachment IDs so that theme creators would have more control over the image's display.  Serving different sizes and/or retrieving alt text, etc.

**Comment by NlGhT** [comment]
I have the following
/**
 * I use the options framework to upload an image and get the url
 * to $imgURL
 */
$imgURL = of_get_option("uploader",get_template_directory_uri()."/img/banner_home.jpg");
/**
 * I use the function that Davin put above to get the ID of that image
 * (I do not mind about the image resolution because I will work on 
 * that later)
 * to $imgID
 */
$imgID = prefix_get_attachment_id_from_url( $imgURL );
/**
 * $imgTAG is going to be a string variable that will contains an 
 * HTML markup tag such as: <img src="" height="" width="">. 
 * It is a wp function that returns this.
 * Example: <img src="" height="" width="">. It is a wp function that returns this.
 * The parameter "full" will get the full version, other parameters get lower  
 * resolution. refer to the codex for more
 */
$imgTAG = wp_get_attachment_image($epk_image_id,'full');
/**
 * Now we extract the necessary data from that tag
 * $imgATTRIBUTE[0] = src
 * $imgATTRIBUTE[1] = width
 * $imgATTRIBUTE[2] = height
 */
$imgATTRIBUTE = NlGhT_get_img_attributes ($imgTAG);

/**
 * The following function returns an array with the img attributes
 */
function NlGhT_get_img_attributes($url){
		//$html = file_get_contents($url);

		$doc = new DOMDocument();
		$doc->loadHTML($url/*$html*/);
		$xpath = new DOMXPath($doc);
		$array = array();
		$array[0] = $xpath->evaluate("string(//img/@src)");	
		$array[1] = $xpath->evaluate("string(//img/@width)");
		$array[2] = $xpath->evaluate("string(//img/@height)");
		return $array;
}

**Comment by tameroski** [comment]
+1 on that new "media" option. Would be way better for accessing media attributes.
