### ISSUE TITLE
Link button

### ISSUE THREAD

**Issue by everlast000** [devinsays/options-framework-plugin#204]
Is it me or is there not a Link/Unlink button in the wysiwyg editor? It does appear on the "text" tab, but it's not there in de "wysiwyg" tab.

**Comment by devinsays** [comment]
This was also mentioned in an e-mail:

I noticed the visual text editor doesn't have a link button. Only the text view does. I tried for over an hour to get the link button in but I could not. I've looked up tinymce documentation but nothing is working for me to get that button in. For developers it's no problem clicking the text view to add the links, but I was thinking from a users view point who is not a developer. They will see that there is not link button and think badly of the CMS options. I was wondering if you could point me in the right direction please.

**Comment by devinsays** [comment]
I didn't notice anything specifically related to links, but I will test a few of the settings:
https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-editor.php#L76

**Comment by wpmark** [comment]
I am also experiencing this issue too. I think that this is related somehow to this plugin as if I render a ```wp_editor``` anywhere else using the core function the default is to output the editor with the link buttons present.

**Comment by wpmark** [comment]
It would appear after a little experimenting that this line is causing the problem:

https://github.com/devinsays/options-framework-plugin/blob/master/includes/class-options-interface.php#L356

When I declare in my ```options.php``` file my call to the editor if I do the following this solves the problem:

```
$options[] = array(
		'name'		=> __( 'Footer Text', 'drdd' ),
		'desc'		=> 'Add text to appear on the footer here. Ideal for your copyright info.',
		'id'		=> 'footer_text',
		'type'		=> 'editor',
		'settings' 	=> array(
			'media_buttons' => false,
			'textarea_rows'	=> 5,
			'tinymce' => true
		)
	);
```

Note passing ```true``` to the `tinymce``` part of the settings array.

**Comment by devinsays** [comment]
Okay, thanks for the tip! I'll look into it.

**Comment by rosswintle** [comment]
Hi folks,

Just came across this same thing.

I'm not sure if this is a code issue or a documentation one.  I suspect @wpmark used:

```
$wp_editor_settings = array(
		'wpautop' => true, // Default
		'textarea_rows' => 5,
		'tinymce' => array( 'plugins' => 'wordpress' )
	);
```

because that's one of the examples in [options.php in the options-check example code](https://github.com/devinsays/options-framework-plugin/blob/master/options-check/options.php). That's certainly what I did.

Passing `'tinymce' => array( 'plugins' => 'wordpress')` to `wp_editor()` will override the defaults that `wp_editor()` normally provides. These are (currently in WP 4.1.1) set on [lines 350-367 of wp-includes/class-wp-editor.php](https://core.trac.wordpress.org/browser/tags/4.1.1/src/wp-includes/class-wp-editor.php#L350) and look like:

```
$plugins = array(
  'charmap',
  'colorpicker',
  'hr',
  'lists',
  'media',
  'paste',
  'tabfocus',
  'textcolor',
  'fullscreen',
  'wordpress',
  'wpautoresize',
  'wpeditimage',
  'wpgallery',
  'wplink',
  'wpdialogs',
  'wpview',
);
```

Passing `'tinymce' => true`, or leaving it out so `wp_editor()` uses the default tinymce value, makes `wp_editor()` uses the default tinymce plugins listed above.

I tested this by using `'tinymce' => array( 'plugins' => 'wordpress,wplink')` and I got the link buttons.

That default list of plugins is _probably_ too long (i.e. you probably wouldn't want `wpautoresize` in an options panel), but perhaps the example in options-check could include a useful sub-set?

**Comment by devinsays** [comment]
Thanks for opening this ticket and all the research that went into helping find a solution. I agree that it would be good to have the link buttons by default.

I updated the the examples in options check and also the defaults in interface.php. Props to @rosswintle in the changelog for solution.

Let me know if you encounter any issues with this.
