### ISSUE TITLE
Using the framework in a separated WP Admins page

### ISSUE THREAD

**Issue by gillchristian** [devinsays/options-framework-plugin#217]
HI! First of all thanks for the framework, is really awesome, you have done a pretty cool job with it!

My issue/question is how can I use it to put the theme options in a independet WP Admin page instead under the appearance menu?

I hope I did not miss it, maybe it was somewhere in the documentation or easy to find in the code but I was not able to find the way to do it.

Thanks!

EDIT: also is there a way to grab the options declaration from say `/some-folder-inside-the-theme/my-options-file.php` instead of doing it from `options.php`.

**Comment by devinsays** [comment]
Hi. Sorry for the delayed response.

Yes you can! You'll need to filter than params here: https://github.com/devinsays/options-framework-plugin/blob/master/includes/class-options-framework-admin.php#L118

Set the 'mode' to "menu" rather than "submenu".

You can also filter the options.php location: https://github.com/devinsays/options-framework-plugin/blob/master/includes/class-options-framework.php#L105
